version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "super-freight-easy"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-ku244e0tqbvq"
s3_prefix = "super-freight-easy"
region = "ap-southeast-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "S3BucketName=\"super-freight-order-file-bucket\" SqsQueueName=\"super-freight-order-file-event-sqs\" SnsTopicName=\"super-freight-order-file-event-topic\" StoreConfigBucketName=\"store-config-bucket\""
