AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  super-freight-easy

  One lambda function to convert the order file to a CSV file that can be imported to the Super Freight system.

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 60

Parameters:
  S3BucketName:
    Type: String
    Description: Name of the S3 Bucket that stores the order file

  SnsTopicName:
    Type: String
    Description: Name of the SNS topic that publishes the order file event

Resources:
  GenerateSuperFreightCsvFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: app/
      Handler: app.lambdaHandler
      Runtime: nodejs12.x
      Policies:
        - AWSLambdaExecute
        - S3CrudPolicy:
            BucketName: !Ref S3BucketName
      Events:
        OrderFileUploaded:
          Type: SNS # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Topic: !Sub "arn:aws:sns:${AWS::Region}:${AWS::AccountId}:${SnsTopicName}"

Outputs:
  GenerateSuperFreightCsvFunction:
    Description: "Generate Super Freight Csv Lambda Function ARN"
    Value: !GetAtt GenerateSuperFreightCsvFunction.Arn
  GenerateSuperFreightCsvFunctionIamRole:
    Description: "Implicit IAM Role created for Generate Super Freight Csv Function"
    Value: !GetAtt GenerateSuperFreightCsvFunctionRole.Arn
